### ISSUE TITLE
Problem in description

### ISSUE THREAD

**Issue by jasonaltenburg** [exDeos/hello-world#2]
_Used ahk to create some custom "small-shop" applications._

I'm pretty sure those were enterprise grade.

**Comment by exDeos** [comment]
Quotes were included to denote ambiguity. The apps met a localized demand; to avoid conflation of *enterprise-grade* and *enterprise-wide*, avoiding the token 'enterpise' seems indicated.

They were hopefully well written and met that demand for many years.
